export type Photo = {
  // Photo ID (unique). It will also become the URL slug.
  id: number | string
  // Photo title
  title: string
  // Photo URL (can be absolute or relative to the public folder)
  url: string
  // Photo description
  description: string
}

// Photos 1-10: excerpts from Propaganda (1928) by Edward Bernays
// Photos 11-100: excerpts generated by ChatGPT
export const photos: Photo[] = [
  {
    id: 1,
    title: 'Masses',
    url: '/img/1.jpg',
    description:
      'The instruments by which public opinion is organized and focused may be misused. But such organization and focusing are necessary to orderly life.',
  },
  {
    id: 2,
    title: 'Invisible',
    url: '/img/2.jpg',
    description:
      'As civilization has become more complex, and as the need for invisible government has been increas ingly demonstrated, the technical means have been invented and developed by which opinion may be regimented.',
  },
  {
    id: 3,
    title: 'Expense',
    url: '/img/3.jpg',
    description:
      'The invisible government tends to be concentrated in the hands of the few because of the expense of manipulating the social machinery which controls the opinions and habits of the masses.',
  },
  {
    id: 4,
    title: 'Mechanism',
    url: '/img/4.jpg',
    description:
      'No matter how sophisticated, how cynical the public may become about publicity methods, it must respond to the basic appeals, because it will always need food, crave amusement, long for beauty, respond to leadership.',
  },
  {
    id: 5,
    title: 'Millions',
    url: '/img/5.jpg',
    description:
      'This practice of creating circumstances and of creating pictures in the minds of millions of persons is very common.',
  },
  {
    id: 6,
    title: 'Continuous',
    url: '/img/6.jpg',
    description:
      'The important thing is that it is universal and continuous; and in its sum total it is regimenting the public mind every bit as much as an army regiments the bodies of its soldiers.',
  },
  {
    id: 7,
    title: 'Irresistible',
    url: '/img/7.jpg',
    description:
      'When regimented, a group at times offers an irresistible pressure before which legislators, editors, and teachers are helpless.',
  },
  {
    id: 8,
    title: 'Pressure',
    url: '/img/8.jpg',
    description:
      'A desire for a specific reform, however widespread, cannot be translated into action until it is made articulate, and until it has exerted sufficient pressure upon the proper law-making bodies.',
  },
  {
    id: 9,
    title: 'Interests',
    url: '/img/9.jpg',
    description:
      'In the active proselytizing minorities in whom selfish interests and public interests coincide lie the progress and development of America.',
  },
  {
    id: 10,
    title: 'Think',
    url: '/img/10.jpg',
    description:
      'Small groups of persons can, and do, make the rest of us think what they please about a given subject.',
  },
  {
    id: 11,
    title: 'Manipulation',
    url: '/img/11.jpg',
    description:
      'The conscious and intelligent manipulation of the organized habits and opinions of the masses is an important element in democratic society.',
  },
  {
    id: 12,
    title: 'Leadership',
    url: '/img/12.jpg',
    description:
      'The quality of leadership can often determine the fate of collective endeavors.',
  },
  {
    id: 13,
    title: 'Propaganda',
    url: '/img/13.jpg',
    description:
      'The word propaganda has been stigmatized, but its original meaning was neutral and related to dissemination of information.',
  },
  {
    id: 14,
    title: 'Information',
    url: '/img/14.jpg',
    description: 'An informed public is essential for a functioning democracy.',
  },
  {
    id: 15,
    title: 'Consent',
    url: '/img/15.jpg',
    description:
      'The engineering of consent is the essence of the democratic process.',
  },
  {
    id: 16,
    title: 'Power',
    url: '/img/16.jpg',
    description:
      'Power is increasingly concentrated in the hands of a few, whether in politics or industry.',
  },
  {
    id: 17,
    title: 'Ideas',
    url: '/img/17.jpg',
    description: 'Ideas are the starting points of all human actions.',
  },
  {
    id: 18,
    title: 'Publicity',
    url: '/img/18.jpg',
    description:
      'Publicity, in its most basic form, represents the actions of making something public knowledge.',
  },
  {
    id: 19,
    title: 'Democracy',
    url: '/img/19.jpg',
    description: 'Democracy depends on an informed and engaged citizenry.',
  },
  {
    id: 20,
    title: 'Opinion',
    url: '/img/20.jpg',
    description:
      'Opinions are often formed under the influence of those who hold power.',
  },
  {
    id: 21,
    title: 'Crisis',
    url: '/img/21.jpg',
    description:
      'In times of crisis, propaganda efforts often intensify to rally public opinion.',
  },
  {
    id: 22,
    title: 'Influence',
    url: '/img/22.jpg',
    description: 'The media plays a crucial role in shaping public opinion.',
  },
  {
    id: 23,
    title: 'Ignorance',
    url: '/img/23.jpg',
    description:
      'Ignorance can often be more damaging than outright deception.',
  },
  {
    id: 24,
    title: 'Perception',
    url: '/img/24.jpg',
    description: 'Perception is often reality in the world of public opinion.',
  },
  {
    id: 25,
    title: 'Voice',
    url: '/img/25.jpg',
    description:
      'The voice of the people must be heard for true democracy to flourish.',
  },
  {
    id: 26,
    title: 'Freedom',
    url: '/img/26.jpg',
    description:
      'Freedom of expression is a cornerstone of democratic societies.',
  },
  {
    id: 27,
    title: 'Control',
    url: '/img/27.jpg',
    description: 'Control of information is control of the public.',
  },
  {
    id: 28,
    title: 'Trust',
    url: '/img/28.jpg',
    description: 'Trust must be earned and is easily lost.',
  },
  {
    id: 29,
    title: 'Ethics',
    url: '/img/29.jpg',
    description: 'The ethics of propaganda are frequently questioned.',
  },
  {
    id: 30,
    title: 'Society',
    url: '/img/30.jpg',
    description:
      'Propaganda shapes not just individual opinions, but the structure of society itself.',
  },
  {
    id: 31,
    title: 'Tradition',
    url: '/img/31.jpg',
    description:
      'Tradition plays a significant role in shaping public opinion.',
  },
  {
    id: 32,
    title: 'Belief',
    url: '/img/32.jpg',
    description:
      'Beliefs are often more potent than facts in influencing human behavior.',
  },
  {
    id: 33,
    title: 'Identity',
    url: '/img/33.jpg',
    description: 'Identity is a key factor in how we interpret propaganda.',
  },
  {
    id: 34,
    title: 'Innovation',
    url: '/img/34.jpg',
    description:
      'New technologies can influence the effectiveness of propaganda methods.',
  },
  {
    id: 35,
    title: 'Choice',
    url: '/img/35.jpg',
    description:
      'The illusion of choice can be a powerful tool in shaping public opinion.',
  },
  {
    id: 36,
    title: 'Conformity',
    url: '/img/36.jpg',
    description:
      'Conformity to group norms can overshadow individual critical thinking.',
  },
  {
    id: 37,
    title: 'Authority',
    url: '/img/37.jpg',
    description:
      'The authority figure often has a disproportionate influence on public opinion.',
  },
  {
    id: 38,
    title: 'Fear',
    url: '/img/38.jpg',
    description:
      'Fear is often used as a motivator for public action or inaction.',
  },
  {
    id: 39,
    title: 'Hope',
    url: '/img/39.jpg',
    description:
      'Hope can also be a powerful motivator in shaping public opinion.',
  },
  {
    id: 40,
    title: 'Change',
    url: '/img/40.jpg',
    description: 'Public opinion is never static and is susceptible to change.',
  },
  {
    id: 41,
    title: 'Conflict',
    url: '/img/41.jpg',
    description: 'Conflict often creates an atmosphere ripe for propaganda.',
  },
  {
    id: 42,
    title: 'Unity',
    url: '/img/42.jpg',
    description: 'Propaganda can either divide or unify a population.',
  },
  {
    id: 43,
    title: 'Ignorance',
    url: '/img/43.jpg',
    description:
      'Ignorance is not just a lack of knowledge but also a societal condition.',
  },
  {
    id: 44,
    title: 'Reality',
    url: '/img/44.jpg',
    description:
      'What is considered real is often a construction of societal beliefs.',
  },
  {
    id: 45,
    title: 'Moral',
    url: '/img/45.jpg',
    description: 'Moral convictions can both resist and facilitate propaganda.',
  },
  {
    id: 46,
    title: 'Freedom',
    url: '/img/46.jpg',
    description:
      'Freedom can sometimes be compromised in the name of security.',
  },
  {
    id: 47,
    title: 'Diversity',
    url: '/img/47.jpg',
    description: 'Diverse perspectives are essential for a balanced society.',
  },
  {
    id: 48,
    title: 'Debate',
    url: '/img/48.jpg',
    description: 'Debate is often seen as a means to arrive at the truth.',
  },
  {
    id: 49,
    title: 'Youth',
    url: '/img/49.jpg',
    description: 'The youth are not just the future, but also the present.',
  },
  {
    id: 50,
    title: 'Experience',
    url: '/img/50.jpg',
    description:
      'Life experiences significantly shape our perspectives and susceptibilities.',
  },
  {
    id: 51,
    title: 'Persuasion',
    url: '/img/51.jpg',
    description: 'Persuasion is often more effective than force.',
  },
  {
    id: 52,
    title: 'History',
    url: '/img/52.jpg',
    description:
      'History is often written by the victors, influencing future generations.',
  },
  {
    id: 53,
    title: 'Silence',
    url: '/img/53.jpg',
    description: 'Silence can sometimes speak louder than words.',
  },
  {
    id: 54,
    title: 'Voice',
    url: '/img/54.jpg',
    description:
      'The freedom to raise one’s voice is a fundamental human right.',
  },
  {
    id: 55,
    title: 'Media',
    url: '/img/55.jpg',
    description:
      'The role of media cannot be understated in shaping public opinion.',
  },
  {
    id: 56,
    title: 'Fact',
    url: '/img/56.jpg',
    description:
      'Facts are often less influential in shaping public opinion than emotions.',
  },
  {
    id: 57,
    title: 'Bias',
    url: '/img/57.jpg',
    description:
      'Every individual has a bias shaped by their life experiences.',
  },
  {
    id: 58,
    title: 'Democracy',
    url: '/img/58.jpg',
    description:
      'The balance between freedom and security is a delicate one in democratic societies.',
  },
  {
    id: 59,
    title: 'Transparency',
    url: '/img/59.jpg',
    description: 'Transparency can often alleviate concerns and build trust.',
  },
  {
    id: 60,
    title: 'Future',
    url: '/img/60.jpg',
    description:
      'The future is shaped by the actions and beliefs we hold today.',
  },
  {
    id: 61,
    title: 'Adaptation',
    url: '/img/61.jpg',
    description:
      'Adaptation to changing times is crucial for societal progress.',
  },
  {
    id: 62,
    title: 'Empathy',
    url: '/img/62.jpg',
    description:
      'Empathy can transcend barriers and create shared understanding.',
  },
  {
    id: 63,
    title: 'Mystery',
    url: '/img/63.jpg',
    description:
      'The unknown often holds a mysterious allure in shaping opinions.',
  },
  {
    id: 64,
    title: 'Social',
    url: '/img/64.jpg',
    description: 'Social dynamics play a major role in shaping our views.',
  },
  {
    id: 65,
    title: 'Integrity',
    url: '/img/65.jpg',
    description: 'Integrity is often at the core of public trust.',
  },
  {
    id: 66,
    title: 'Sacrifice',
    url: '/img/66.jpg',
    description:
      'The notion of sacrifice can mobilize communities for a cause.',
  },
  {
    id: 67,
    title: 'Heritage',
    url: '/img/67.jpg',
    description: 'Cultural heritage can be a source of pride and identity.',
  },
  {
    id: 68,
    title: 'Obligation',
    url: '/img/68.jpg',
    description: 'Feelings of obligation can drive public action.',
  },
  {
    id: 69,
    title: 'Dialogue',
    url: '/img/69.jpg',
    description: 'Dialogue can be a pathway to resolving conflicts.',
  },
  {
    id: 70,
    title: 'Community',
    url: '/img/70.jpg',
    description: 'The community often reflects the values of its individuals.',
  },
  {
    id: 71,
    title: 'Rebellion',
    url: '/img/71.jpg',
    description: 'Rebellion can be a catalyst for societal change.',
  },
  {
    id: 72,
    title: 'Memory',
    url: '/img/72.jpg',
    description: 'Collective memory shapes how societies view the present.',
  },
  {
    id: 73,
    title: 'Passion',
    url: '/img/73.jpg',
    description: 'Passion can be infectious and rally people to a cause.',
  },
  {
    id: 74,
    title: 'Isolation',
    url: '/img/74.jpg',
    description: 'Isolation can create vulnerabilities to propaganda.',
  },
  {
    id: 75,
    title: 'Conviction',
    url: '/img/75.jpg',
    description: 'Strong convictions can either unite or divide.',
  },
  {
    id: 76,
    title: 'Perception',
    url: '/img/76.jpg',
    description: 'Perception often becomes reality in the minds of many.',
  },
  {
    id: 77,
    title: 'Wisdom',
    url: '/img/77.jpg',
    description: 'Wisdom often comes from a multiplicity of perspectives.',
  },
  {
    id: 78,
    title: 'Hierarchy',
    url: '/img/78.jpg',
    description: 'Hierarchical structures can influence public behavior.',
  },
  {
    id: 79,
    title: 'Exposure',
    url: '/img/79.jpg',
    description: 'Exposure to diverse views can enrich our understanding.',
  },
  {
    id: 80,
    title: 'Technology',
    url: '/img/80.jpg',
    description: 'Technology is a double-edged sword in shaping opinion.',
  },
  {
    id: 81,
    title: 'Global',
    url: '/img/81.jpg',
    description: 'Global events often ripple through local communities.',
  },
  {
    id: 82,
    title: 'Resistance',
    url: '/img/82.jpg',
    description: 'Resistance can be a response to oppressive ideas.',
  },
  {
    id: 83,
    title: 'Evolution',
    url: '/img/83.jpg',
    description: 'Ideas evolve over time, as does their impact.',
  },
  {
    id: 84,
    title: 'Power',
    url: '/img/84.jpg',
    description: 'Power dynamics are always at play in shaping narratives.',
  },
  {
    id: 85,
    title: 'Spirituality',
    url: '/img/85.jpg',
    description: 'Spirituality often influences ethical and moral views.',
  },
  {
    id: 86,
    title: 'Legitimacy',
    url: '/img/86.jpg',
    description: 'The question of legitimacy often arises in public discourse.',
  },
  {
    id: 87,
    title: 'Alienation',
    url: '/img/87.jpg',
    description:
      'Alienation can make individuals susceptible to extreme views.',
  },
  {
    id: 88,
    title: 'Nostalgia',
    url: '/img/88.jpg',
    description: 'Nostalgia can affect how people view the present and future.',
  },
  {
    id: 89,
    title: 'Humanity',
    url: '/img/89.jpg',
    description: 'A sense of shared humanity can counteract division.',
  },
  {
    id: 90,
    title: 'Responsibility',
    url: '/img/90.jpg',
    description:
      'Collective responsibility is a concept that can mobilize or stifle.',
  },
  {
    id: 91,
    title: 'Action',
    url: '/img/91.jpg',
    description: 'Action speaks louder than words in shaping public opinion.',
  },
  {
    id: 92,
    title: 'Nature',
    url: '/img/92.jpg',
    description:
      'The natural world often serves as a backdrop for human drama.',
  },
  {
    id: 93,
    title: 'Influence',
    url: '/img/93.jpg',
    description: 'Influence is not just wielded by those in power.',
  },
  {
    id: 94,
    title: 'Confidence',
    url: '/img/94.jpg',
    description: 'Confidence can be persuasive in its own right.',
  },
  {
    id: 95,
    title: 'Uncertainty',
    url: '/img/95.jpg',
    description: 'Uncertainty can either paralyze or galvanize a population.',
  },
  {
    id: 96,
    title: 'Mindset',
    url: '/img/96.jpg',
    description:
      'Individual mindset contributes to collective action or inaction.',
  },
  {
    id: 97,
    title: 'Limits',
    url: '/img/97.jpg',
    description: 'Understanding limits can be empowering in its own right.',
  },
  {
    id: 98,
    title: 'Empowerment',
    url: '/img/98.jpg',
    description: 'Empowerment of individuals can lead to collective action.',
  },
  {
    id: 99,
    title: 'Transparency',
    url: '/img/99.jpg',
    description: 'Transparency can build or erode trust in public figures.',
  },
  {
    id: 100,
    title: 'Legacy',
    url: '/img/100.jpg',
    description: 'The legacy left behind can influence generations to come.',
  },
]
