export type Photo = {
  // Photo ID (unique). It will also become the URL slug.
  id: number | string
  // Photo title
  title: string
  // Photo URL (can be absolute or relative to the public folder)
  url: string
  // Photo description
  description: string
}

// Photos 1-10: excerpts from Propaganda (1928) by Edward Bernays
// Photos 11-30: excerpts generated by ChatGPT
export const photos: Photo[] = [
  {
    id: 1,
    title: 'Masses',
    url: '/img/1.jpg',
    description:
      'The instruments by which public opinion is organized and focused may be misused. But such organization and focusing are necessary to orderly life.',
  },
  {
    id: 2,
    title: 'Invisible',
    url: '/img/2.jpg',
    description:
      'As civilization has become more complex, and as the need for invisible government has been increas ingly demonstrated, the technical means have been invented and developed by which opinion may be regimented.',
  },
  {
    id: 3,
    title: 'Expense',
    url: '/img/3.jpg',
    description:
      'The invisible government tends to be concentrated in the hands of the few because of the expense of manipulating the social machinery which controls the opinions and habits of the masses.',
  },
  {
    id: 4,
    title: 'Mechanism',
    url: '/img/4.jpg',
    description:
      'No matter how sophisticated, how cynical the public may become about publicity methods, it must respond to the basic appeals, because it will always need food, crave amusement, long for beauty, respond to leadership.',
  },
  {
    id: 5,
    title: 'Millions',
    url: '/img/5.jpg',
    description:
      'This practice of creating circumstances and of creating pictures in the minds of millions of persons is very common.',
  },
  {
    id: 6,
    title: 'Continuous',
    url: '/img/6.jpg',
    description:
      'The important thing is that it is universal and continuous; and in its sum total it is regimenting the public mind every bit as much as an army regiments the bodies of its soldiers.',
  },
  {
    id: 7,
    title: 'Irresistible',
    url: '/img/7.jpg',
    description:
      'When regimented, a group at times offers an irresistible pressure before which legislators, editors, and teachers are helpless.',
  },
  {
    id: 8,
    title: 'Pressure',
    url: '/img/8.jpg',
    description:
      'A desire for a specific reform, however widespread, cannot be translated into action until it is made articulate, and until it has exerted sufficient pressure upon the proper law-making bodies.',
  },
  {
    id: 9,
    title: 'Interests',
    url: '/img/9.jpg',
    description:
      'In the active proselytizing minorities in whom selfish interests and public interests coincide lie the progress and development of America.',
  },
  {
    id: 10,
    title: 'Think',
    url: '/img/10.jpg',
    description:
      'Small groups of persons can, and do, make the rest of us think what they please about a given subject.',
  },
  {
    id: 11,
    title: 'Manipulation',
    url: '/img/11.jpg',
    description:
      'The conscious and intelligent manipulation of the organized habits and opinions of the masses is an important element in democratic society.',
  },
  {
    id: 12,
    title: 'Leadership',
    url: '/img/12.jpg',
    description:
      'The quality of leadership can often determine the fate of collective endeavors.',
  },
  {
    id: 13,
    title: 'Propaganda',
    url: '/img/13.jpg',
    description:
      'The word propaganda has been stigmatized, but its original meaning was neutral and related to dissemination of information.',
  },
  {
    id: 14,
    title: 'Information',
    url: '/img/14.jpg',
    description: 'An informed public is essential for a functioning democracy.',
  },
  {
    id: 15,
    title: 'Consent',
    url: '/img/15.jpg',
    description:
      'The engineering of consent is the essence of the democratic process.',
  },
  {
    id: 16,
    title: 'Power',
    url: '/img/16.jpg',
    description:
      'Power is increasingly concentrated in the hands of a few, whether in politics or industry.',
  },
  {
    id: 17,
    title: 'Ideas',
    url: '/img/17.jpg',
    description: 'Ideas are the starting points of all human actions.',
  },
  {
    id: 18,
    title: 'Publicity',
    url: '/img/18.jpg',
    description:
      'Publicity, in its most basic form, represents the actions of making something public knowledge.',
  },
  {
    id: 19,
    title: 'Democracy',
    url: '/img/19.jpg',
    description: 'Democracy depends on an informed and engaged citizenry.',
  },
  {
    id: 20,
    title: 'Opinion',
    url: '/img/20.jpg',
    description:
      'Opinions are often formed under the influence of those who hold power.',
  },
  {
    id: 21,
    title: 'Crisis',
    url: '/img/21.jpg',
    description:
      'In times of crisis, propaganda efforts often intensify to rally public opinion.',
  },
  {
    id: 22,
    title: 'Influence',
    url: '/img/22.jpg',
    description: 'The media plays a crucial role in shaping public opinion.',
  },
  {
    id: 23,
    title: 'Ignorance',
    url: '/img/23.jpg',
    description:
      'Ignorance can often be more damaging than outright deception.',
  },
  {
    id: 24,
    title: 'Perception',
    url: '/img/24.jpg',
    description: 'Perception is often reality in the world of public opinion.',
  },
  {
    id: 25,
    title: 'Voice',
    url: '/img/25.jpg',
    description:
      'The voice of the people must be heard for true democracy to flourish.',
  },
  {
    id: 26,
    title: 'Freedom',
    url: '/img/26.jpg',
    description:
      'Freedom of expression is a cornerstone of democratic societies.',
  },
  {
    id: 27,
    title: 'Control',
    url: '/img/27.jpg',
    description: 'Control of information is control of the public.',
  },
  {
    id: 28,
    title: 'Trust',
    url: '/img/28.jpg',
    description: 'Trust must be earned and is easily lost.',
  },
  {
    id: 29,
    title: 'Ethics',
    url: '/img/29.jpg',
    description: 'The ethics of propaganda are frequently questioned.',
  },
  {
    id: 30,
    title: 'Society',
    url: '/img/30.jpg',
    description:
      'Propaganda shapes not just individual opinions, but the structure of society itself.',
  },
]
